### ISSUE TITLE
pre-v5 branch request

### ISSUE THREAD

**Issue by riquezjp** [lwfinger/rtw89#10]
Congrats & thanks! for making this driver which is a life saver for me.
It works for Lenovo Thinkbook 14 G2 (amd) ryzen5 4500 with (intel wifi6) aka: RealTek 8852 on Manjaro KDE 21.0.7 & both Ubuntu 20.04 LTS & 21.04.
I have had intermittant connection drops which are fixed by a quick wifi Off/On.
So far on Ub 21.04 I had no connection drops, fingers crossed.

Right after I installed 21.04 today (2021.07.03), you updated to v5. I would like to request you make the previous version  published again, as that is good for me. I can fork it & use it as a safe base. (As I should have already)

Your instructions were clear & easy, even for me. Im truly greatful for your work with this.

**Comment by lwfinger** [comment]
One of the joys of git is that you can always get an earlier version. 'git checkout 8f6b38fd88088756e1a1' will get you v4. Note that that version leaks memory and has other bugs that are fixed in v5.
