### ISSUE TITLE
TIP How to install rtw89 to arch/manjaro

### ISSUE THREAD

**Issue by XOMUS** [lwfinger/rtw89#101]
`sudo pacman -Sy linux???-headers yay`
`sudo pacman -Syu dkms base-devel --needed`
??? - you kernel version
`yay -Sy rtw89-dkms-git`
pls  lwfinger add to readme.md

**Comment by lwfinger** [comment]
Done. Thanks.

**Comment by jonathonf** [comment]
> yay -Sy

This is terrible. Let me file a PR to improve the help for Arch-based distros.
