### ISSUE TITLE
try to compile on linux 4.18 but fail

### ISSUE THREAD

**Issue by siyy123** [lwfinger/rtw89#104]
[make.log](https://github.com/lwfinger/rtw89/files/7776474/make.log)

**Comment by XOMUS** [comment]
You on arch/manjaro?

**Comment by XOMUS** [comment]
sudo pacman -Sy linux-$(uname -r)-headers yay
sudo pacman -Syu dkms base-devel --needed
yay -Sy rtw89-dkms-git

restart your pc/notebook

**Comment by XOMUS** [comment]
And done

**Comment by siyy123** [comment]
No I'm on centos 8 :(

**Comment by XOMUS** [comment]
OK wait

**Comment by XOMUS** [comment]
Try this and install
sudo yum install kernel-headers kernel-devel
sudo yum group install "C Development Tools and Libraries"

**Comment by siyy123** [comment]
I'm sure that the procedures are not wrong, and this issue is only for helping backport. The kernel on centos 8 is too old. Though I can try elrepo kernels or use centos9, the kernels are not properly signed for secure boot and can't boot on my computer:(

**Comment by XOMUS** [comment]
Use arch or manjaro cent os from servers

**Comment by XOMUS** [comment]
Or debian

**Comment by XOMUS** [comment]
Or mint mate

**Comment by XOMUS** [comment]
https://media.tenor.com/images/1e144c0ed826a3fb112b1b18c75cedf1/tenor.gif

**Comment by siyy123** [comment]
ok i know but just make the issue clear.

**Comment by XOMUS** [comment]
Something is missing for make

**Comment by XOMUS** [comment]
Try sudo yum install make gcc linux-headers-$(uname -r) build-essential git

**Comment by lwfinger** [comment]
The problem is that his kernel is 4.18, and so far, I support only back to 5.4 for this driver. @XOMUS - I know you are trying to be helpful, but you need to watch a bit more before trying to help.
