### ISSUE TITLE
New commits break signing on Debian 11

### ISSUE THREAD

**Issue by eshimoniak** [lwfinger/rtw89#111]
The most recent commit that successfully signs is cf95d903e9d78b395cf7d7744acac1170b903af5

The output of `sudo make sign-install` is as follows:
```
make -C /lib/modules/5.10.0-10-amd64/build M=/home/eshimoniak/loose-packages/firmware/rtw89 modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-10-amd64'
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-10-amd64'
echo "Skipping key creation"
Skipping key creation
At main.c:291:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: rtw89usb.ko: No such file or directory
make: *** [Makefile:101: sign] Error 1
```

Installing `libssl-dev` didn't fix the issue.

I'm dual booting with Fedora 35, and the issue does not exist there.

**Comment by lwfinger** [comment]
I removed some early usb driver attempts and forgot to remove the signing of the usb kernel module. My fault.

Do another pull, and you should be OK.
