### ISSUE TITLE
Bluetooth Still Nonfuntional

### ISSUE THREAD

**Issue by ShaunTheQuietGamer** [lwfinger/rtw89#119]
I know this isn't the *correct* place to put this, but I have no idea where upstream even is. My bluetooth is still not working, `lsusb` shows ```Bus 003 Device 003: ID 0bda:4852 Realtek Semiconductor Corp. Bluetooth Radio```

I saw this ID mentioned, but I'm not sure if its in the driver or not, and don't know how to check. It seemed like every time it was mentioned it was on an issue that had been closed for 3 months, and so no one saw it.

**Comment by lwfinger** [comment]
That device is, or soon will be, in btusb for newer kernels. Just last week, it was merged with the 5.16 and 5.15 stable kernels, and is in the 5.17-rcX kernel. No BT stuff is in this driver, which is for wifi, not BT.
