### ISSUE TITLE
not an issue only a good news about backport on ubuntu

### ISSUE THREAD

**Issue by gpdevsoft** [lwfinger/rtw89#123]
on *ubuntu 20.04 LTS distros kernel received an update from 5.11 to 5.13 and after reboot wifi card still work, so i think ubuntu's developers have backported Realtek 8852AE driver on 5.13 kernel, but i don't know how to retreive the driver version

**Comment by lwfinger** [comment]
The driver does not report a version. Just use it, and if problems exist, this repo has the newest code and may fix your troubles.
