### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by hyperboly** [lwfinger/rtw89#124]
I can make rtw89 on Popos, but when I try to sudo modprobe -v rtw89, it reads:

modprobe: FATAL: Module rtw89 not found in /lib/modules/5.15.5-76051505

It doesn't work even if I try changing the name to rtw89pci.
Please help. thanks.

**Comment by lwfinger** [comment]
Did you do 'sudo make install'? The correct name is rtw89pci, not rtw89.

**Comment by hyperboly** [comment]
Thanks! This solved my issue.
