### ISSUE TITLE
Can't update for new kernel

### ISSUE THREAD

**Issue by Leviathan13186** [lwfinger/rtw89#138]
I'm on Pop 21.10 and just updated to 5.16.15-76051615-generic. I tried doing the usual git pull for the new kernel and I got this,

The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Not sure how to correct this. The wifi seems to be working but its having the weird disconnect issue but I already created the config file from last time so I'm a bit lost :/

**Comment by lwfinger** [comment]
GitHub keeps changing their security. Before now, it had only affected uploads, but now anonymous git:// downloads are forbidden. In .git/config, change "git://" to "https://" and it should work. Let me know here.
