### ISSUE TITLE
Last commit rtw89: Fix build for kernels older that 5.4 is wrong

### ISSUE THREAD

**Issue by StefanGottwald** [lwfinger/rtw89#141]
There are some typos in the commit c7ceb31fbdeb5d2a848180a880e0efcc06fe356c as the lines with:

#if LINUX_VERSION_CODE >= KERNEL_VERSION(5. 4, 0)

should be

#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 4, 0)

So , instead of . here.

**Comment by lwfinger** [comment]
Thanks. I fixed it before I got to @KLDM's posting in my E-mail.
