### ISSUE TITLE
`make` fail on clear linux

### ISSUE THREAD

**Issue by wilnguyen** [lwfinger/rtw89#185]
![image](https://user-images.githubusercontent.com/61312884/201015115-8265e754-cd06-43db-a69a-975c96da3ef2.png)
I tried many times. 
My environment is a fresh clear linux (desktop). Then install hardward-wifi / dev bundles but no hopes.

Can you guild me how can I give more information to you? Like a debug flags for more tracing logs?

**Comment by lwfinger** [comment]
You have not installed the kernel headers. Read that section of README.md.

**Comment by wilnguyen** [comment]
many thank @lwfinger . I installed the kernel-dev bundles (~16Gb) which including kernel headers and it work perfectly now.
