### ISSUE TITLE
Skipping BTF generation due to unavailability of vmlinux 

### ISSUE THREAD

**Issue by dia2e2** [lwfinger/rtw89#187]
Anyone knows why I keep getting this error.
Am i supposed to upgrade the kernel version.

make -C /lib/modules/5.15.0-52-generic/build M=/home/alex modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-52-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  You are using:           gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  CC [M]  /home/alex/test.o
  MODPOST /home/alex/Module.symvers
  CC [M]  /home/alex/test.mod.o
  LD [M]  /home/alex/test.ko
  BTF [M] /home/alex/test.ko
Skipping BTF generation for /home/alex/test.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-52-generic'

**Comment by lwfinger** [comment]
Do not worry about it. You could get rid of those warnings, but you would have to build your own kernel, and I doubt that you wish to do this. You can operate very well without BTF. Google it if you do not believe me.
