### ISSUE TITLE
Build error on kernel 5.4

### ISSUE THREAD

**Issue by nuagetec** [lwfinger/rtw89#190]
Hello,

I have the fallowing issue to buid on ubuntu 18 and kernel 5.4 :

make VERBOSE=1
make -C /lib/modules/5.4.0-132-generic/build M=/home/kevin/Documents/Wifi_driver/rtw89 modules
make[1] : on entre dans le répertoire « /usr/src/linux-headers-5.4.0-132-generic »
  CC [M]  /home/kevin/Documents/Wifi_driver/rtw89/core.o
In file included from /home/kevin/Documents/Wifi_driver/rtw89/cam.h:8:0,
                 from /home/kevin/Documents/Wifi_driver/rtw89/core.c:7:
/home/kevin/Documents/Wifi_driver/rtw89/core.h:4431:18: warning: ‘struct cfg80211_tid_config’ declared inside parameter list will not be visible outside of this definition or declaration
           struct cfg80211_tid_config *tid_config);
                  ^~~~~~~~~~~~~~~~~~~
/home/kevin/Documents/Wifi_driver/rtw89/core.c:2609:19: warning: ‘struct cfg80211_tid_cfg’ declared inside parameter list will not be visible outside of this definition or declaration
            struct cfg80211_tid_cfg *tid_conf)
                   ^~~~~~~~~~~~~~~~
/home/kevin/Documents/Wifi_driver/rtw89/core.c: In function ‘_rtw89_core_set_tid_config’:
/home/kevin/Documents/Wifi_driver/rtw89/core.c:2613:21: error: dereferencing pointer to incomplete type ‘struct cfg80211_tid_cfg’
  u32 mask = tid_conf->mask;
                     ^~
In file included from ./include/linux/bitops.h:5:0,
                 from ./include/linux/kernel.h:12,
                 from ./include/linux/skbuff.h:13,
                 from ./include/linux/ip.h:16,
                 from /home/kevin/Documents/Wifi_driver/rtw89/core.c:4:
/home/kevin/Documents/Wifi_driver/rtw89/core.c:2628:18: error: ‘NL80211_TID_CONFIG_ATTR_AMPDU_CTRL’ undeclared (first use in this function); did you mean ‘NL80211_MESHCONF_ATTR_MAX’?
   if (mask & BIT(NL80211_TID_CONFIG_ATTR_AMPDU_CTRL)) {
                  ^
./include/linux/bits.h:8:30: note: in definition of macro ‘BIT’
 #define BIT(nr)   (UL(1) << (nr))
                              ^~
/home/kevin/Documents/Wifi_driver/rtw89/core.c:2628:18: note: each undeclared identifier is reported only once for each function it appears in
   if (mask & BIT(NL80211_TID_CONFIG_ATTR_AMPDU_CTRL)) {
                  ^
./include/linux/bits.h:8:30: note: in definition of macro ‘BIT’
 #define BIT(nr)   (UL(1) << (nr))
                              ^~
/home/kevin/Documents/Wifi_driver/rtw89/core.c:2629:27: error: ‘NL80211_TID_CONFIG_ENABLE’ undeclared (first use in this function); did you mean ‘NL80211_CMD_CONN_FAILED’?
    if (tid_conf->ampdu == NL80211_TID_CONFIG_ENABLE) {
                           ^~~~~~~~~~~~~~~~~~~~~~~~~
                           NL80211_CMD_CONN_FAILED
/home/kevin/Documents/Wifi_driver/rtw89/core.c: At top level:
/home/kevin/Documents/Wifi_driver/rtw89/core.c:2654:18: warning: ‘struct cfg80211_tid_config’ declared inside parameter list will not be visible outside of this definition or declaration
           struct cfg80211_tid_config *tid_config)
                  ^~~~~~~~~~~~~~~~~~~
/home/kevin/Documents/Wifi_driver/rtw89/core.c:2652:6: error: conflicting types for ‘rtw89_core_set_tid_config’
 void rtw89_core_set_tid_config(struct rtw89_dev *rtwdev,
      ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/kevin/Documents/Wifi_driver/rtw89/cam.h:8:0,
                 from /home/kevin/Documents/Wifi_driver/rtw89/core.c:7:
/home/kevin/Documents/Wifi_driver/rtw89/core.h:4429:6: note: previous declaration of ‘rtw89_core_set_tid_config’ was here
 void rtw89_core_set_tid_config(struct rtw89_dev *rtwdev,
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/kevin/Documents/Wifi_driver/rtw89/core.c: In function ‘rtw89_core_set_tid_config’:
/home/kevin/Documents/Wifi_driver/rtw89/core.c:2658:28: error: dereferencing pointer to incomplete type ‘struct cfg80211_tid_config’
  for (i = 0; i < tid_config->n_tid_conf; i++)
                            ^~
/home/kevin/Documents/Wifi_driver/rtw89/core.c: In function ‘rtw89_core_register_hw’:
/home/kevin/Documents/Wifi_driver/rtw89/core.c:3357:13: error: ‘struct wiphy’ has no member named ‘tid_config_support’; did you mean ‘bss_select_support’?
  hw->wiphy->tid_config_support.vif |= BIT(NL80211_TID_CONFIG_ATTR_AMPDU_CTRL);
             ^~~~~~~~~~~~~~~~~~
             bss_select_support
In file included from ./include/linux/bitops.h:5:0,
                 from ./include/linux/kernel.h:12,
                 from ./include/linux/skbuff.h:13,
                 from ./include/linux/ip.h:16,
                 from /home/kevin/Documents/Wifi_driver/rtw89/core.c:4:
/home/kevin/Documents/Wifi_driver/rtw89/core.c:3357:43: error: ‘NL80211_TID_CONFIG_ATTR_AMPDU_CTRL’ undeclared (first use in this function); did you mean ‘NL80211_MESHCONF_ATTR_MAX’?
  hw->wiphy->tid_config_support.vif |= BIT(NL80211_TID_CONFIG_ATTR_AMPDU_CTRL);
                                           ^
./include/linux/bits.h:8:30: note: in definition of macro ‘BIT’
 #define BIT(nr)   (UL(1) << (nr))
                              ^~
/home/kevin/Documents/Wifi_driver/rtw89/core.c:3358:13: error: ‘struct wiphy’ has no member named ‘tid_config_support’; did you mean ‘bss_select_support’?
  hw->wiphy->tid_config_support.peer |= BIT(NL80211_TID_CONFIG_ATTR_AMPDU_CTRL);
             ^~~~~~~~~~~~~~~~~~
             bss_select_support
scripts/Makefile.build:270: recipe for target '/home/kevin/Documents/Wifi_driver/rtw89/core.o' failed
make[2]: *** [/home/kevin/Documents/Wifi_driver/rtw89/core.o] Error 1
Makefile:1765: recipe for target '/home/kevin/Documents/Wifi_driver/rtw89' failed
make[1]: *** [/home/kevin/Documents/Wifi_driver/rtw89] Error 2
make[1] : on quitte le répertoire « /usr/src/linux-headers-5.4.0-132-generic »
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

Any idea ?

Kevin

**Comment by lwfinger** [comment]
Kernel 5.4 is too old. There are too many deficiencies. Even if those were fixed, the wifi would be slow because necessary feature for high-speed performance are missing.

 I am only supporting 5.5 or newer. Upgrade your kernel!
