### ISSUE TITLE
Unable to build on Fedora 37

### ISSUE THREAD

**Issue by Craftzman7** [lwfinger/rtw89#197]
When attempting to build the driver on Fedora 37 I get the following error
```
make -C /lib/modules/6.0.7-301.fc37.x86_64/build M=/home/crafter/rtw89/rtw89 modules
make[1]: *** /lib/modules/6.0.7-301.fc37.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:86: all] Error 2
```
I made sure I installed the packages needed that are specified in the README file.

**Comment by lwfinger** [comment]
I created a new virtual machine running Fedora 37, and the necessary link was created.

What does 'uname -r' show?

**Comment by Craftzman7** [comment]
Updating my kernel resolved the issue.
