### ISSUE TITLE
manjaro linux6.0.15-1 Realtek8852BE may have a problem

### ISSUE THREAD

**Issue by lijun1234567** [lwfinger/rtw89#205]
![深度截图_选择区域_20221227222644](https://user-images.githubusercontent.com/118330699/209681137-b1ab6b26-c12a-40fc-8dab-4a117dd0e0d1.png)
I write this to load the module .
But my computer still can not detect and connect wireless network

**Comment by lijun1234567** [comment]
when in linux 6.1.1-1 ,it's ok

**Comment by lwfinger** [comment]
You need to run 'sudo modprobe -v rtw_8852be'. What you did was 'sudo modprobe -v' and modprobe had no idea what driver to load.
