### ISSUE TITLE
RTL8852BE Bluetooth support?

### ISSUE THREAD

**Issue by TheMiningTeamYT** [lwfinger/rtw89#207]
I have an RTL8852BE in my new laptop and I've been using the rtw89 driver with it under Linux Mint 21.1. The WiFi has been working great, but the Bluetooth, not so much. Based on my readings, the RTL8852BE also provides the Bluetooth radio in this laptop, so I was wondering: Will the rtw89 driver will ever support the RTL8852BE's Bluetooth radio? Thanks!
(Thanks for providing such a great WiFi all around, and thanks in advance for any help you can give.)

**Comment by lwfinger** [comment]
I guess that you realized that the wifi driver is not the Bluetooth driver. They are separate devices, even though they live in the same chip and share the 2.4 GHz radio. The wifi driver only needs to coexist with the BT.
