### ISSUE TITLE
not working on Ubuntu 22.04 (v5.15.x). alternative repo

### ISSUE THREAD

**Issue by nlkguy** [lwfinger/rtw89#208]
https://github.com/HRex39/rtl8852be works for v5.15 22.04 .

**Comment by lwfinger** [comment]
Then use that driver. It is the vendor driver, and contains a lot of code that is not needed for standard usage. I do not believe that HRex39 is maintaining it any longer, thus you will need to fix any changes in kernel API when a you get a newer kernel.
