### ISSUE TITLE
How to blacklist kernel versions?

### ISSUE THREAD

**Issue by PrinceSidon** [lwfinger/rtw89#215]
Hello I am trying to install this driver in Pop!_OS 22.04 on an HP Laptop 14, which uses RTL 8852be. I completed the installation but I noticed that you mentioned in the readme page that you have to blacklist your kernel version if you are using kernels 5.16+. I am using 6.0.12-76060006-generic. How do I blacklist my kernel version? Please let me know. Thanks!

**Comment by lwfinger** [comment]
Do an Internet search for "Linux blacklist module" and pick one of the responses for your distro version.
