### ISSUE TITLE
Direct firmware load for rtw89/rtw8852a_fw.bin failed with error -2

### ISSUE THREAD

**Issue by ArdityaWildan** [lwfinger/rtw89#220]
Hello,
I have a problem with this library on my debian 11 (Linux 6.1.11 x86_64) device
It doesn't seem to work, found below in kern.log :
`rtw89_8852ae 0000:01:00.0: Direct firmware load for rtw89/rtw8852a_fw.bin failed with error -2`

lspci :
`01:00.0 Network controller: Realtek Semiconductor Co., Ltd. Device 8852
	DeviceName: WLAN
	Subsystem: Hewlett-Packard Company Device 88e1
	Flags: fast devsel, IRQ 24, IOMMU group 10
	I/O ports at 2000 [size=256]
	Memory at d0800000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: <access denied>
	Kernel modules: rtw_8852ae`

lsmod | grep rtw :
![image](https://user-images.githubusercontent.com/88582395/218045977-f8d95b5c-8e5e-4998-bee6-077ca2581651.png)

thanks for your attention

**Comment by ArdityaWildan** [comment]
Sorry, I have found a solution for this problem by downloading that related bin manually

**Comment by lwfinger** [comment]
Your distro should have provided it automatically.

Be aware that with compressed firmware, which is the normal form, the driver will get a failure when it tries to load the uncompressed one directly, and then succeeds when it loads the compressed form indirectly. As you only provided that one line from dmesg, I cannot tell you if that is what was happening.
