### ISSUE TITLE
Module conflict as of kernel 6.2

### ISSUE THREAD

**Issue by mauricioquintela** [lwfinger/rtw89#224]
RTW8852BE driver support (and probably the other two, not sure) is now in mainline kernel as of 6.2. 
Making this issue as it is fundamental to uninstall this repo's module when updating, as the conflict will crash the kernel (at least on arch). 
Thank you for the support until now, @lwfinger !

**Comment by lwfinger** [comment]
Drivers for RTW8852AE and RTW8852CE were in an earlier kernel. The BE is new.  The need to be careful when both are available is covered in README.md
