### ISSUE TITLE
Ubuntu will not have drivers?

### ISSUE THREAD

**Issue by Bakai-Taalaibek** [lwfinger/rtw89#231]
HI, so this guy @ https://github.com/HRex39/rtl8852be said that if we have kernel >6 we should look at your solution, but you basically say that Ubuntu will not be supported. Does it mean that we should not upgrade to kernel 6 and further if we want working wifi?

**Comment by lwfinger** [comment]
I did not say that Ubuntu would not be supported; however, Ubuntu haqs a bad habit of backporting kernel API changes from the newest kernels to older ones. If such backporting breaks the build, I will not fix it as such changes would break everyone else. Kernels 6.1 and 6.2 have the 8852be driver built in, so no need to use this repo for tmem UNLESS you want the latest changes and fixes. The code here is what will be in kernel 6.4.
