### ISSUE TITLE
8852BU driver

### ISSUE THREAD

**Issue by Fishwaldo** [lwfinger/rtw89#234]
Hi,
Just want to confirm that the USB variant of the 8852 wifi chip isn't supported? (I see the usb.c/h files in the repo, but excluded from complication?) 

If it's not supported, any tips what needs to be done to get it working again?

**Comment by lwfinger** [comment]
It is not supported. Those files are part of my first aattempt to add the support. The attempt failed, and the files were inadvertently included in the repo.
