### ISSUE TITLE
Kernel files

### ISSUE THREAD

**Issue by andreichalapco** [lwfinger/rtw89#237]
What is the difference between these files and the rtw89 files present on the source cocde of the linux kernel?

**Comment by lwfinger** [comment]
These files are more up to date than any kernel that you will be using. At the moment, this repo has the code that will be in the 6.4 kernel, which will not be released until late June or early July. A major difference is that kernels 6.3 and 6.3 will not support the USB or SDIO variants, which this repo does.

One other substantial difference is that this repo has conditional compiler directives to allow it to build on older kernels while the in-kernel code only builds on the current kernel.
