### ISSUE TITLE
dmesg errors for rtl 8852be

### ISSUE THREAD

**Issue by boxerab** [lwfinger/rtw89#238]
Thanks so much for maintaining these drivers - wouldn't have wifi connectivity otherwise.

I installed the driver following instructions in this link :
https://discussion.fedoraproject.org/t/how-to-install-the-driver-for-wifi-chip-rtl8852be/68307

```
sudo dnf install git dkms kernel-devel openssl
sudo git clone https://github.com/lwfinger/rtw89.git \
/usr/src/rtw89-git
sudo sed -e "/^MAKE/d;/^CLEAN/d
/^DEST_MODULE_LOCATION/s|/updates/|/extra|" \
/usr/src/rtw89-git/debian/rtw89-dkms.dkms \
| sudo tee /usr/src/rtw89-git/dkms.conf > /dev/null
sudo dkms add rtw89/git
sudo systemctl restart dkms.service
sudo tee /etc/modules-load.d/rtw89.conf << EOF > /dev/null
rtw_8852be
EOF
sudo systemctl restart systemd-modules-load.service
```

I have errors in dmesg, but wifi works. Is there a way of fixing these errors ?

```
[    4.718748] rtw89_8852be 0000:02:00.0: Direct firmware load for rtw89/rtw8852b_fw-1.bin failed with error -2
[    4.718771] rtw89_8852be 0000:02:00.0: Direct firmware load for rtw89/rtw8852b_fw.bin failed with error -2
[    4.718773] rtw89_8852be 0000:02:00.0: failed to early request firmware: -2
[    4.718835] rtw89_8852be 0000:02:00.0: enabling device (0000 -> 0003)
[    4.728344] Error: Driver 'rtw89_8852be' is already registered, aborting...
[    4.728384] snd_pci_acp6x 0000:34:00.5: enabling device (0000 -> 0002)
[    4.733272] rtw89_8852be 0000:02:00.0: Firmware version 0.29.29.0, cmd version 0, type 5
[    4.733275] rtw89_8852be 0000:02:00.0: Firmware version 0.29.29.0, cmd version 0, type 3
```

This is for a Lenovo Thinkbook 16p gen3 laptop.

Thanks!

**Comment by lwfinger** [comment]
Your user-space code is starting the driver twice. That is not the driver's fault. If you cannot find the reason, it is safe to ignore everything here. Do you see the same thing if you do a reboot?

**Comment by boxerab** [comment]
Thanks, I think the reason is that I ran the install script twice,  since I got an error the first time after 
`sudo systemctl restart systemd-modules-load.service`
