### ISSUE TITLE
[AP] regulatory Domain is N/A

### ISSUE THREAD

**Issue by helperShang** [lwfinger/rtw89#243]
## Used as AP ,Why regulatory Domain is N/A

![1010b3505018539761505a8b7090d878](https://user-images.githubusercontent.com/5444154/236984212-ea551590-a553-427b-b0c4-36e6a97044bd.jpg)

- iw reg get                                                                                                                     <main>
```
global
country CN: DFS-FCC
	(2402 - 2482 @ 40), (N/A, 30), (N/A)
	(5170 - 5250 @ 80), (N/A, 30), (N/A), AUTO-BW
	(5250 - 5330 @ 80), (N/A, 30), (0 ms), DFS, AUTO-BW
	(5735 - 5835 @ 80), (N/A, 30), (N/A)
	(57240 - 59400 @ 2160), (N/A, 30), (N/A)
	(59400 - 63720 @ 2160), (N/A, 30), (N/A)
	(63720 - 65880 @ 2160), (N/A, 30), (N/A)
```
- lspci -v
```
0002:21:00.0 Network controller: Realtek Semiconductor Co., Ltd. Device b852
	Subsystem: Hewlett-Packard Company Device 88e3
	Flags: bus master, fast devsel, latency 0, IRQ 207
	I/O ports at 1000 [size=256]
	Memory at f2200000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: [40] Power Management version 3
	Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [70] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [148] Device Serial Number 00-e0-4c-ff-fe-88-52-01
	Capabilities: [158] Latency Tolerance Reporting
	Capabilities: [160] L1 PM Substates
	Kernel driver in use: rtw89_8852be
	Kernel modules: rtw_8852be
```

**Comment by lwfinger** [comment]
Is that regulatory domain set before rtw_8852be is loaded?
I have a file /usr/lib/modprobe.d/70-cfg80211.conf that contains the line "options cfg80211 ieee80211_regdom=US". That sets my regulatory domain before any wireless drivers are loaded. If you already have such a configuration file, then the utility may not know how to interrogate it correctly. The place where regulatory domain errors shows up in the 5G band. The default configuration will have all channels flagged with "(no IR)", which will prevent the AP from broadcasting beacons. If your setup is  working, then the utility is wrong.
