### ISSUE TITLE
Can it work on kernel 4.9?

### ISSUE THREAD

**Issue by yangchaohong** [lwfinger/rtw89#251]
I have bought a BPI-W2 router.It is based on RTD1296 chip.Sadly RTD1296 has little support from mainline kernel.So I have use 4.9 bsp kernel.I have tryed another driver by HRex39(https://github.com/HRex39/rtl8852be).It can be compiled but it doesn't work.Sadly,that repository has been archived.So I had to turn to you.

**Comment by brianwitte** [comment]
Hi, @yangchaohong. This repo covers only 5.7 and above at this time.
