### ISSUE TITLE
rtw_8852be is listed twice in debian/rtw89-dkms.dkms

### ISSUE THREAD

**Issue by mst2020** [lwfinger/rtw89#252]
Hello, there is a minor error:

https://github.com/lwfinger/rtw89/blob/8f8efa64ba3f9ee1c1b8a90e68d6f6a8c7872d6f/debian/rtw89-dkms.dkms#L10
https://github.com/lwfinger/rtw89/blob/8f8efa64ba3f9ee1c1b8a90e68d6f6a8c7872d6f/debian/rtw89-dkms.dkms#L14

this leads to a (non critical?) notice:

> Module version  for rtw_8852be.ko
> exactly matches what is already found in kernel 6.1.0-9-amd64.
> DKMS will not replace this module.
> You may override by specifying --force.

**Comment by lwfinger** [comment]
The second one should have been rtw8851be.
