### ISSUE TITLE
Gole1 pro mini pc

### ISSUE THREAD

**Issue by zekoslavmrkva** [lwfinger/rtw89#254]
Touch screen not working anymore, drivers are installed correctly, disabled enabled installed uninstalled, everything tried and, in the bios, now is only 2.0 ghz speed of processor. It was 2.7. What can be? Thanx

**Comment by lwfinger** [comment]
None of these issues have anything to do with wireless. I have no idea what might be causing them.

My only suggestion would be to re-install the operating system, or even try a different distro.
