### ISSUE TITLE
Makefile need inspection about 8851be

### ISSUE THREAD

**Issue by ohquait** [lwfinger/rtw89#261]
@lwfinger 
acual git i see a differ in MAkefile:
you add:
obj-m += rtw_8851b.o
rtw_8851b-y := rtw8851b.o \
		    rtw8851b_table.o \
		    rtw8851b_rfk.o \
		    rtw8851b_rfk_table.o

obj-m += rtw_8851be.o
rtw_8851be-y := rtw8851be.o

but on the end of file:
@$(KSRC)/scripts/sign-file sha256 MOK.priv MOK.der rtw89core.ko
@$(KSRC)/scripts/sign-file sha256 MOK.priv MOK.der rtw89pci.ko
@$(KSRC)/scripts/sign-file sha256 MOK.priv MOK.der rtw_8852a.ko
@$(KSRC)/scripts/sign-file sha256 MOK.priv MOK.der rtw_8852ae.ko
@$(KSRC)/scripts/sign-file sha256 MOK.priv MOK.der rtw_8852b.ko
@$(KSRC)/scripts/sign-file sha256 MOK.priv MOK.der rtw_8852be.ko
@$(KSRC)/scripts/sign-file sha256 MOK.priv MOK.der rtw_8852c.ko
@$(KSRC)/scripts/sign-file sha256 MOK.priv MOK.der rtw_8852ce.ko

there is nothing for rtw_8851be, it is right?

**Comment by lwfinger** [comment]
Yes, I forgot to add the 8851b and 8851be drivers to the signing section. I do not use secure boot, thus I never missed it. Now fixed.
