### ISSUE TITLE
8852BE Bluetooth broken since kernel 6.4

### ISSUE THREAD

**Issue by Jusix** [lwfinger/rtw89#272]
Since kernel 6.3 my 8852BE was working perfectly fine. But since kernel 6.4.0 and up until now with kernel 6.5.5 Bluetooth is going crazy. All devices are getting disconnected and immediately reconnected every few seconds.

![Bildschirmfoto vom 2023-10-04 21-15-08](https://github.com/lwfinger/rtw89/assets/8763014/0409af6d-59ae-4b13-9b01-ae8d43f61a02)

```
01:00.0 Network controller: Realtek Semiconductor Co., Ltd. Device b852
	Subsystem: Device 1d3e:c826
	Flags: bus master, fast devsel, latency 0, IRQ 98, IOMMU group 11
	I/O ports at 2000 [size=256]
	Memory at c0900000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: <access denied>
	Kernel driver in use: rtw89_8852be
	Kernel modules: rtw89_8852be
```

**Comment by lwfinger** [comment]
You are using the driver from the kernel, and probably the BT driver from there as well. What do you expect us to do for you?
