### ISSUE TITLE
Build Debian package missing "/debian" directory

### ISSUE THREAD

**Issue by liorzilp** [lwfinger/rtw89#283]
The build of the Debian package is broken.
In order to create a Debian package using dpkg-buildpackage a specific structure is required.
Explanation and example can be found in:
https://github.com/FooBarWidget/debian-packaging-for-the-modern-developer/blob/master/tutorial-2/README.md#the-dpkg-buildpackage-workflow

**Comment by Hareis** [comment]
yes, i hava some  problem，i download that [https://github.com/peasoft/rtw89-kali](url), that have debian directory

**Comment by EnercoopJNE** [comment]
Same issue here, building the package would be very convenient... In the link provided by Hareis the repo is the one we are on here if I'm not mistaken.

**Comment by lwfinger** [comment]
If you want a new feature, please submit an update to the  code. My time is limited.
