### ISSUE TITLE
ubuntu20.04 Linux 5.16.5 how can I solve this problem?

### ISSUE THREAD

**Issue by majiaqi669** [lwfinger/rtw89#305]
ubuntu20.04 Linux 5.16.5 how can I solve this problem?
![9b218143-8397-4ded-9472-d8716d0554bb](https://github.com/lwfinger/rtw89/assets/102477304/f2918415-71dd-4dfa-9e6c-f158f6d4afb0)
![4271cc11-6e3d-4df0-be50-4e2463e47338](https://github.com/lwfinger/rtw89/assets/102477304/127cd58f-2e09-49e3-b3dd-d5732066771e)
thank you so much!

**Comment by majiaqi669** [comment]
if I use old kernel I will meet another error
![2c3a4f10-2d00-460c-84ef-89c4927c4a49](https://github.com/lwfinger/rtw89/assets/102477304/e78319bc-65b3-41c3-97b2-825268110d46)

**Comment by lwfinger** [comment]
I fixed the problem with kernel 5.10. Your problem with 5.15 is that your version of gcc is a lot older than the one used to compile the kernrl. That is not allowed.

**Comment by majiaqi669** [comment]
thank you so much,It's solved!
