### ISSUE TITLE
Issue with Kernel 6.6.x

### ISSUE THREAD

**Issue by gpastal24** [lwfinger/rtw89#307]
Hello,

The drivers do not seem to work for Linux Kernel 6.6.x.
When I try to modprobe the module it says "error: device is busy".
When I load kernel 5.15.x they work fine.

Do you have any idea what is going on here?

**Comment by lwfinger** [comment]
Yes.  You have interference between the drivers in the kernel and those in this repo. With 6.6, you do NOT need this repo. Use the in-kernel drivers.

**Comment by gpastal24** [comment]
You are the best , thanks

**Comment by privacyfreak84** [comment]
How do I use the in kernel drivers after building this one?

**Comment by privacyfreak84** [comment]
How do I use the in kernel drivers after building this one?

**Comment by gpastal24** [comment]
@privacyfreak84
Sudo make uninstall inside rwt889

**Comment by privacyfreak84** [comment]
I did that but it didn’t fix anything. WiFi still isn’t back. I just made an issue about it: https://github.com/lwfinger/rtw89/issues/311
