### ISSUE TITLE
Just a hint for README.md no issue.

### ISSUE THREAD

**Issue by sgse** [lwfinger/rtw89#31]
Hallo,
your wonderful driver is in repositories (chaotic-aur) too.

![2021-08-05_16-38](https://user-images.githubusercontent.com/17575778/128369052-7dfeeaa6-4309-4ac3-8a24-da64ec33b54e.png)

This eliminates the need to build after a kernel update, just tested, works :-) .

greetings
SGS

**Comment by XOMUS** [comment]
I asked lwfinger to add instructions for installing arch/manjaro
