### ISSUE TITLE
Is this compatible with 8832cu?

### ISSUE THREAD

**Issue by lilkidsuave** [lwfinger/rtw89#317]
title

**Comment by lwfinger** [comment]
No, this repo does not yet handle any USB devices. My guess is that you need https://github.com:lwfinger/rtw8852cu.git, but without the USB ID from 'lsusb', I cannot tell.

**Comment by Megachip** [comment]
> USB ID from 'lsusb

ID 0bda:c832 Realtek 802.11ax WLAN Adapter

**Comment by lilkidsuave** [comment]
Why exactly
