### ISSUE TITLE
rtw8852be: signature and/or required key missing - tainting kernel

### ISSUE THREAD

**Issue by TroyeJames9** [lwfinger/rtw89#326]
OS: ubuntu22.04.4 LTS
Kernel version: 5.15.0-101-generic
motherboard：[ASUS B760M AYW WIFI D4](https://www.asus.com/motherboards-components/motherboards/others/b760m-ayw-wifi-d4/)

- WLAN has been enabled in BIOS settings

- I use the `lsmod | grep rtw`, the output as follow:

```
rtw_8852be             16384  0
rtw_8852b             409600  1 rtw_8852be
rtw89pci               81920  1 rtw_8852be
rtw89core             770048  2 rtw89pci,rtw_8852b
mac80211             1249280  2 rtw89pci,rtw89core
cfg80211              974848  3 rtw89core,mac80211,rtw_8852b
```

- the dmesg.txt is follow:

[dmesg_log.txt](https://github.com/lwfinger/rtw89/files/14809639/dmesg_log.txt)

The error about rtw8852 in dmesg is as follows:
![Snipaste_2024-03-30_09-52-13](https://github.com/lwfinger/rtw89/assets/130838331/0b7642e3-97bf-48a5-afe1-d85db644c4bb)

- The results of  `mokutil --sb-state` are as follows. I have disabled secure boot:

```
SecureBoot disabled
Platform is in Setup Mode
```

I'm just one step away from success. Please help me. I'm sorry to bother you.

**Comment by TroyeJames9** [comment]
我使用了以下安装教程来进行安装的
![Snipaste_2024-03-30_10-18-11](https://github.com/lwfinger/rtw89/assets/130838331/62231401-eaf1-486b-a9fd-df5307efdd21)

**Comment by lwfinger** [comment]
There is a known problem with Ubuntu 22.04. In the rtw89 directory,

git checkout 6dc944
make
sudo make

That should work for you.
