### ISSUE TITLE
Are version tags planned in this repo? 

### ISSUE THREAD

**Issue by realnickel** [lwfinger/rtw89#33]
Hi!
Thank you for your work.
I'd like to create an RPM package with the driver and wish to know which versioning scheme do you plan to use?
Would it be "v5", "v6" or something different?
Do you plan to tag releases?

**Comment by lwfinger** [comment]
Until the driver is accepted into mainline, I will create a new branch to match the "revision" level of the submission. After testing, that code will be copied into the main branch, thus main is the only branch you need to use. There will not be  an official version, and the releases will not be tagged. Once the driver is accepted into mainline, only the main branch will remain, and updates to the kernel code will be ported to this repo. Set up your RPM spec file to pull this repo.

**Comment by realnickel** [comment]
Thanks a lot.
