### ISSUE TITLE
Problem with make sign-install command

### ISSUE THREAD

**Issue by Leviathan13186** [lwfinger/rtw89#40]
Hey guys, sorry if this is a simple issue I'm super new to linux. I'm running Kubuntu and followed all the steps and on the last one I got this output ,"make: *** No rule to make target 'sign-install'.  Stop." Is there something I did wrong?

**Comment by sh1n0b1** [comment]
I had the same problem. Here's how I resolve this:
1. Follow [this](https://ubuntu.com/blog/how-to-sign-things-for-secure-boot) create and entroll a self-sign cert/key to MOK (Make sure to reboot and enroll the key during boot up). Make sure the key got added by running "cat /proc/keys" and search for the common name of the cert you specified in your openssl.cnf file. 
2. run "make install" on the code, skip the "sign-install" command
3. Sign the two module.ko file (rtw89pci.ko and rtw89core.ko)
4. "sudo modprobe rtw89pci"

**Comment by strangebreww** [comment]
That's because `sign-install` is missing in `v5` branch atm. Possible workaround is to clone the main branch instead.

**Comment by lwfinger** [comment]
v6 will not build on older kernels either. I have been busy with another project.

**Comment by Leviathan13186** [comment]
> I had the same problem. Here's how I resolve this:
> 
> 1. Follow [this](https://ubuntu.com/blog/how-to-sign-things-for-secure-boot) to create and enroll a self-sign cert/key to MOK (Make sure to reboot and enroll the key during boot up). Make sure the key got added by running "cat /proc/keys" and search for the common name of the cert you specified in your openssl.cnf file. 
> 
> 2. run "make install" on the code, skip the "sign-install" command
> 
> 3. Sign the two module.ko file (rtw89pci.ko and rtw89core.ko)
> 
> 4. "sudo modprobe rtw89pci"

Thank you I'll try this! So just copy paste the commands under kernels and bootloaders in that link right? Is the sudo mod probe the command that signs the two module.ko?

**Comment by sh1n0b1** [comment]
> > I had the same problem. Here's how I resolve this:
> > 
> > 1. Follow [this](https://ubuntu.com/blog/how-to-sign-things-for-secure-boot) to create and enroll a self-sign cert/key to MOK (Make sure to reboot and enroll the key during boot up). Make sure the key got added by running "cat /proc/keys" and search for the common name of the cert you specified in your openssl.cnf file.
> > 2. run "make install" on the code, skip the "sign-install" command
> > 3. Sign the two module.ko file (rtw89pci.ko and rtw89core.ko)
> > 4. "sudo modprobe rtw89pci"
> 
> Thank you I'll try this! So just copy paste the commands under kernels and bootloaders in that link right? Is the sudo mod probe the command that signs the two module.ko?

No, the command to sign the module is: "kmodsign sha512 MOK.priv MOK.der module.ko"
Replace "module.ko" with the two module files. Follow the guide.

**Comment by sh1n0b1** [comment]
> > I had the same problem. Here's how I resolve this:
> > 
> > 1. Follow [this](https://ubuntu.com/blog/how-to-sign-things-for-secure-boot) to create and enroll a self-sign cert/key to MOK (Make sure to reboot and enroll the key during boot up). Make sure the key got added by running "cat /proc/keys" and search for the common name of the cert you specified in your openssl.cnf file.
> > 2. run "make install" on the code, skip the "sign-install" command
> > 3. Sign the two module.ko file (rtw89pci.ko and rtw89core.ko)
> > 4. "sudo modprobe rtw89pci"
> 
> Thank you I'll try this! So just copy paste the commands under kernels and bootloaders in that link right? Is the sudo mod probe the command that signs the two module.ko?

No, the command to sign the module is: "kmodsign sha512 MOK.priv MOK.der module.ko"
Replace "module.ko" with the two module files. Follow the guide.

**Comment by Leviathan13186** [comment]
Ok so i tried with the no "sign-install" and just did "install" and that worked. Probably should have tried that first before going on here. But thank you for helping at least!! thank you all !

**Comment by lukinoway** [comment]
In case you are not running Ubuntu based system, in my case Fedora, check out #38.
Was struggling to find out how to fix it and wrote my "how to" over there.
