### ISSUE TITLE
P2P mode support

### ISSUE THREAD

**Issue by C0rn3j** [lwfinger/rtw89#46]
I am currently running on 5.13.13 against the [current latest commit](https://github.com/lwfinger/rtw89/commit/17d957accfb1302cd989b4fb5645c1fd338e2736).

Following Arch Wiki's [Miracast](https://wiki.archlinux.org/title/Miracast) page [this is the output](https://haste.rys.pw/husovavobi.yaml) of `iw [phy|dev]`.

Notably support for P2P is missing - on 21H1 build of W10 I can at least attempt to connect to the TV (which fails for whatever reason), but on Linux tools like `GNOME Network Displays` straight out refuse to work since they don't see a device with P2P support:

```
Supported interface modes:
         * managed
         * monitor
```

Is the support missing from whatever sources Realtek is providing or does the chip just plain out does not support P2P mode?

EDIT: Switched to Intel AX200 due to this issue and another high ping issue and Miracast now works fine.

**Comment by lwfinger** [comment]
P2P is now available for rtw89.
