### ISSUE TITLE
random networck trans hang, need restart wifi interface to recover

### ISSUE THREAD

**Issue by tmsi-io** [lwfinger/rtw89#54]
Hi, i'm legion R7000 latop user,sometimes connected wifi cannot access network ,but single strong and full, i'd have to restart wifi interface to recover,  at same times the kernel message like this:
<pre>
debian kernel: [31481.878540] rtw89_pci 0000:04:00.0: FW status = 0x65008000
debian kernel: [31481.878544] rtw89_pci 0000:04:00.0: FW BADADDR = 0x0
debian kernel: [31481.878547] rtw89_pci 0000:04:00.0: FW EPC/RA = 0x0
debian kernel: [31481.878550] rtw89_pci 0000:04:00.0: FW MISC = 0xb898faa3
debian kernel: [31481.878553] rtw89_pci 0000:04:00.0: R_AX_HALT_C2H = 0x10
debian kernel: [31481.878555] rtw89_pci 0000:04:00.0: R_AX_SER_DBG_INFO = 0x420e000d
debian kernel: [31481.878766] rtw89_pci 0000:04:00.0: --->
debian kernel: [31481.878768] rtw89_pci 0000:04:00.0: R_AX_SER_DBG_INFO =0x420e000d
debian kernel: [31481.878771] rtw89_pci 0000:04:00.0: R_AX_CMAC_ERR_ISR =0x00000000
debian kernel: [31481.878773] rtw89_pci 0000:04:00.0: R_AX_DMAC_ERR_ISR =0x00000000
debian kernel: [31481.878776] rtw89_pci 0000:04:00.0: R_AX_RPQ_RXBD_IDX =0x000a000a
debian kernel: [31481.878778] rtw89_pci 0000:04:00.0: R_AX_DBG_ERR_FLAG=0x00000000
debian kernel: [31481.878780] rtw89_pci 0000:04:00.0: R_AX_LBC_WATCHDOG=0x00000041
debian kernel: [31481.878782] rtw89_pci 0000:04:00.0: quota lost!
debian kernel: [31481.878789] rtw89_pci 0000:04:00.0: DLE group0 empty: 0xffffffff
debian kernel: [31481.878794] rtw89_pci 0000:04:00.0: quota6 rsv/use: 0x14d/0x300
debian kernel: [31481.878797] rtw89_pci 0000:04:00.0: [PLE][CMAC0_RX]min_pgnum=0x164
debian kernel: [31481.878797] rtw89_pci 0000:04:00.0: [PLE][CMAC0_RX]max_pgnum=0x44d
debian kernel: [31481.878800] rtw89_pci 0000:04:00.0: R_AX_HOST_DISPATCHER_ALWAYS_IMR=0x0c000040 
debian kernel: [31481.878802] rtw89_pci 0000:04:00.0: R_AX_HOST_DISPATCHER_ALWAYS_ISR=0x00000000
debian kernel: [31481.878804] rtw89_pci 0000:04:00.0: R_AX_CPU_DISPATCHER_ALWAYS_IMR=0x04000062 
debian kernel: [31481.878807] rtw89_pci 0000:04:00.0: R_AX_CPU_DISPATCHER_ALWAYS_ISR=0x00000000
debian kernel: [31481.878809] rtw89_pci 0000:04:00.0: R_AX_OTHER_DISPATCHER_ALWAYS_IMR=0x00000000 
debian kernel: [31481.878811] rtw89_pci 0000:04:00.0: R_AX_OTHER_DISPATCHER_ALWAYS_ISR=0x00000000
debian kernel: [31481.878812] rtw89_pci 0000:04:00.0: <---
debian kernel: [31481.878813] rtw89_pci 0000:04:00.0: ser event = 0x0010
debian kernel: [31481.946084] rtw89_pci 0000:04:00.0: rtw89: failed to leave lps state
</pre>

**Comment by tmsi-io** [comment]
ps:   kernel version was 5.10, maybe kernel bugs?

**Comment by lwfinger** [comment]
You are getting firmware errors. Some of these are fixed by setting the module option 'disable_aspm_l1=y', 'disable_aspm_l1ss = y', or both may be needed.

**Comment by tmsi-io** [comment]
Ok, will trying set both two options, thanks
