### ISSUE TITLE
make error after updating debian 11 kernel

### ISSUE THREAD

**Issue by kreativkod** [lwfinger/rtw89#63]
Hi,
So I got a kernel update in the last batch of updates to Debian 11 and went for the first time to do the "re-make" of the rtw89 driver.

But his happened.

Do I need to wait for another update of some sort?

peter@lenovo-debian:~$ cd rtw89
peter@lenovo-debian:~/rtw89$ git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
remote: Enumerating objects: 126, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 45 (delta 39), reused 38 (delta 32), pack-reused 0
Unpacking objects: 100% (45/45), 14.49 KiB | 183.00 KiB/s, done.
From https://github.com/lwfinger/rtw89
   3e1148d..2758909  v5         -> origin/v5
   17d957a..3f4822b  main       -> origin/main
   64e6e48..a44bed5  v6         -> origin/v6
 * [new branch]      v7         -> origin/v7
Updating 3e1148d..2758909
Fast-forward
 cam.c | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
peter@lenovo-debian:~/rtw89$ make
make -C /lib/modules/5.10.0-9-amd64/build M=/home/peter/rtw89 modules
make[1]: *** /lib/modules/5.10.0-9-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:52: all] Error 2
peter@lenovo-debian:~/rtw89$ sudo make install
[sudo] password for peter: 
make -C /lib/modules/5.10.0-9-amd64/build M=/home/peter/rtw89 modules
make[1]: *** /lib/modules/5.10.0-9-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:52: all] Error 2
peter@lenovo-debian:~/rtw89$`

**Comment by lwfinger** [comment]
You got more than a kernel update - git was updated as well and the new one is pickier. Run the command that they suggest:
git config pull.rebase false
That will get rid of the messages on the 'git pull'

The error on make is because you do not have the kernel headers installed. I do not know what is required for Debian, but a quick web search should get you that info.

**Comment by AndreasStrahm-Puzzle** [comment]
For me, executing the following command helped in this case:
`PATH=$PATH:/usr/sbin`

**Comment by lwfinger** [comment]
Yes, your problem was unrelated. I find it hard to believe that root on your system did not have /usr/sbin in its path. That should have been available when you did the 'sudo make install', which is the place that depmod is used.

Your BT problem with the stable kernel is one of missing USB IDs. The 5.14 and newer kernels have a patch for two new IDs.

**Comment by kreativkod** [comment]
> The error on make is because you do not have the kernel headers installed. I do not know what is required for Debian, but a quick web search should get you that info.

Maybe I misunderstand, but does not the below suggest that I do have the headers installed?

``` 
peter@lenovo-debian:~/rtw89$ git pull
Already up to date.

peter@lenovo-debian:~/rtw89$ make
make -C /lib/modules/5.10.0-9-amd64/build M=/home/peter/rtw89 modules
make[1]: *** /lib/modules/5.10.0-9-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:52: all] Error 2

peter@lenovo-debian:~/rtw89$ ls -la /lib/modules
total 16
drwxr-xr-x   4 root root 4096 Oct 15 18:38 .
drwxr-xr-x 105 root root 4096 Oct 15 18:37 ..
drwxr-xr-x   3 root root 4096 Oct 15 18:38 5.10.0-8-amd64
drwxr-xr-x   3 root root 4096 Oct 15 18:38 5.10.0-9-amd64

peter@lenovo-debian:~/rtw89$ inxi -S
System:    Host: lenovo-debian Kernel: 5.10.0-9-amd64 x86_64 bits: 64 Desktop: Cinnamon 4.8.6 
           Distro: Debian GNU/Linux 11 (bullseye) 

peter@lenovo-debian:~/rtw89$ 
```

**Comment by shadiakiki1986** [comment]
@kreativkod I installed headers with `apt-get install linux-headers-amd64` but the `make` command still fails. What was the command you used to install the headers?

**Comment by shadiakiki1986** [comment]
nvm. It turns out on debian 11 that the Makefile needed editing to change 
to replace line: `KSRC := /lib/modules/$(KVER)/build`
with: `KSRC := /usr/src/linux-headers-$(KVER)`

Then the `make` and `make install` worked
