### ISSUE TITLE
modprobe: ERROR: could not insert 'rtw89pci': Operation not permitted

### ISSUE THREAD

**Issue by ghost** [lwfinger/rtw89#67]
modprobe: ERROR: could not insert 'rtw89pci': Operation not permitted
i am on ubuntu 21.10
kernel 5.13

**Comment by adityarai** [comment]
I faced the same issue. Please help me out..

**Comment by jdflament** [comment]
Restart your computer, access to the BIOS settings, then disable "Secure Boot", and try again.

**Comment by andrueastman** [comment]
> Restart your computer, access to the BIOS settings, then disable "Secure Boot", and try again.

Thanks!
