### ISSUE TITLE
Unable to create wifi-hotspot as adapter does not support AP (master) mode

### ISSUE THREAD

**Issue by shivamnaik39** [lwfinger/rtw89#69]
this was the tool i was using....
`sudo lnxrouter --ap wlo1 MyAccessPoint -p MyPassPhrase`
`ERROR: Your adapter does not support AP (master) mode`

the output of `iw list` also clearly states that this does not support AP mode but on windows I am able to create wifi-hotspot.
so is there any way I can achieve this on linux, do I need to install some special dependency or different version of particular dependency?  I am currently using **Arch Linux with kernel 5.14.14**. Tried it on LTS kernel as well, it doesn' t work,  btw  wifi and bluetooth works very well with the help of this driver.

**Comment by w407022008** [comment]
I am using a RTL8852AE wireless card and I am experiencing the same problem. Has a solution been found please?

**Comment by lwfinger** [comment]
That feature has not yet been added as most people do not want to turn their $1000 laptop into a $50 router, thus it has very low priority.

If you really need it, buy a $10 wifi dongle with an RT5370 chip in it and base your router on it.

**Comment by w407022008** [comment]
Thx any way, I have another wifi dongle with rtl8812bu..  I will have a test with it.

**Comment by mailinglists35** [comment]
> very low priority.

So this means when you have nothing to and in the right mood you would be able to give this a chance?

I don't have a laptop but a mini pc and I would like to use the mini pcie slot inside it instead of keeping in use and hot an usb port with an usb adapter that works poorer than a pcie chip. Also came here after discovering that the one I wanted doesn't support AP mode on 5GHz (intel ax200)

**Comment by lwfinger** [comment]
You are new here so I will educate you. I did not write the driver. I have no knowledge of the internals of the chip. Even if I wanted to, I would have little idea on what is needed to implement AP mode. My expertise is in the code between the chip and the OS.

If you want a new feature added, follow the instructions in the last paragraph of README.md.

**Comment by mailinglists35** [comment]
thanks @lwfinger for the explanation
I was under the wrong assumption, apologies if this has caused any nuisance.

**Comment by lwfinger** [comment]
No problem. I do try to fix the problems where I have some ability, but adding features is not something I try.
