### ISSUE TITLE
wifi network speed gets super slow after couple of mins.

### ISSUE THREAD

**Issue by adityarai** [lwfinger/rtw89#82]
Hi, I have a new hp 14-ec0000AX laptop with realtek RTL8852AE. Installed ubuntu 21.04 but the wifi speed is super slow and stops working after sometime. Its shows connected but doesn't open up anything and keeps on loading in browser.

**Comment by bjlockie** [comment]
Is there anything in dmesg?
Have you tried the Realtek driver to verify it is a problem with this driver?
