### ISSUE TITLE
Thank you !

### ISSUE THREAD

**Issue by jorismulliez** [lwfinger/rtw89#87]
Thank you lwfinger for your work on this repository !
I bought a new lenovo laptop in september (not specified as ubuntu compatible). And the wifi was not working.
After some research, your repository appeared !
And it worked right away !
I have since done several kernel upgrades and the upgrade of this driver (and branch change if needed) have always worked!

And recently the last kernel installed already contained your driver!

So :clap: and thanks a lot !

Is there a way to sponsor you ?

**Comment by lwfinger** [comment]
It is not my driver. I take the drivers created by Realtek, whose main engineer for these devices is a friend of mine, and put them in a GitHub repo. The only changes I make are to provide conditional changes for things not is the kernel APIs for older kernels.

I have been doing volunteer work for the Linux drivers for Realtek devices for many years, but I do not have any knowledge of the internals of the chips. I like doing this "work", but I have no need for remuneration. I am comfortably retired.
